services:
    cn_pending_actions.pending_actions_service:
        class: ClaviculaNox\PendingActionsBundle\Classes\Services\PendingActionsService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%pending_actions.handlers%"
        calls:
            - [ setContainer,[ "@service_container" ] ]

    cn_pending_actions.pending_actions.service_handler:
        class: ClaviculaNox\PendingActionsBundle\Classes\Handlers\ServiceHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        calls:
            - [ setContainer,[ "@service_container" ] ]

    cn_pending_actions.pending_actions.event_handler:
        class: ClaviculaNox\PendingActionsBundle\Classes\Handlers\EventHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    cn_pending_actions.pending_actions.command_handler:
        class: ClaviculaNox\PendingActionsBundle\Classes\Handlers\CommandHandler
